### ISSUE TITLE
BRUCE-OP repository is 404

### ISSUE THREAD

**Issue by shiba-8ro** [Westwood-Robotics/BRUCE_SENSE#3]
hello. This may not be the right place to write it here, but I would like to report that the BRUCE-OP repository is 404.
![image](https://github.com/Westwood-Robotics/BRUCE_SENSE/assets/5852451/fda996a8-05c3-403b-96a4-53ef159fc683)
![image](https://github.com/Westwood-Robotics/BRUCE_SENSE/assets/5852451/145f28b3-307a-462c-a961-a3ed2292f6b8)

**Comment by xzhang-wr** [comment]
Hi,

BRUCE-OP is currently only open to our customers, developers and community members. It will be opened up to more people once the developer community is well established. 

Thank you for your continuous interest and stay tuned!

**Comment by shiba-8ro** [comment]
Thank you for reply.
I C very well. I wish your project success.
